### ISSUE TITLE
Merging this extension into core JupyterLab

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/jupyterlab-recents#10]
This is a heads up that after discussion on the JupyterLab weekly meeting (participation is welcome, see https://github.com/jupyterlab/team-compass#weekly-jupyterlab-team-meeting) I started working on merging a refactored version of this extension into core jupyterlab. The initial plan was to only move the recents manager, but given that there is very little overhead from having the menu in too, this will be included in the PR for consideration.

I will post a link once the PR is open; it will target JupyterLab 4.2 release. Once merged, this extension could either provide additional functionality (not clear what might be the users desires here) or be archived.

**Comment by jtpio** [comment]
Looks like this repo could then soon be archived, now that https://github.com/jupyterlab/jupyterlab/pull/15483 has been merged and released in the 4.2 beta.

Maybe after the JupyterLab 4.2.0 final release?

**Comment by fcollonval** [comment]
Closing as it was released as part of core JupyterLab starting with version 4.2.0
