### ISSUE TITLE
Update to JupyterLab 4 and Notebook 7

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-recents#7]
## Is your feature request related to a problem? Please describe.

The latest published version of the extension is still for JupyterLab 3:

https://github.com/jupyterlab-contrib/jupyterlab-recents/blob/c9179a760fe9a5d3057138dff26380c792805f31/package.json#L82

## Describe the solution you'd like

Support for JupyterLab 4 and Notebook 7.

## Describe alternatives you've considered

N/A

## Additional context

There is interest in having such feature in the Notebook application: https://github.com/jupyter/notebook/pull/5051

So having this extension available in Notebook 7 would meet the requirements.

**Comment by fcollonval** [comment]
Closed by #8
